name: sanitary_inspector_prep
description: Complete Flutter app for Sanitary Inspector exam preparation
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  cupertino_icons: ^1.0.6
  
  # Local Storage & File Handling
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  
  # PDF Viewing
  syncfusion_flutter_pdfviewer: ^24.2.9
  
  # Utilities
  intl: ^0.19.0
  flutter_spinkit: ^5.2.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/pdfs/
    - assets/icon/
    - assets/data/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1E88E5"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
