name: sanitary_inspector_prep
description: A Flutter app to prepare for Sanitary Inspector exams with notes, quizzes, and PYQs.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/pdfs/
    # Add PDF files/images later

  fonts:
    # Optional: Add font config if needed
    # - family: Roboto
    #   fonts:
    #     - asset: fonts/Roboto-Regular.ttf
