name: sanitary_inspector_app
description: A simple Flutter app for Sanitary Inspector prep.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pdfx: ^2.9.2
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0

flutter:
  assets:
    - assets/pdfs/
    - assets/notes/
    - assets/quizzes/