name: sanitary_inspector_prep
description: A Flutter app for Sanitary Inspector exam preparation with Firebase integration
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Core Dependencies
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_auth: ^4.15.3
  
  # State Management
  provider: ^6.1.1
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  
  # Permissions & File Handling
  permission_handler: ^11.0.1
  file_picker: ^6.1.1
  
  # PDF Viewing
  flutter_pdfview: ^1.3.2
  syncfusion_flutter_pdfviewer: ^23.2.7
  
  # HTTP & Networking
  http: ^1.1.2
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # Utilities
  intl: ^0.18.1
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/pdfs/
    - assets/icon/
    - assets/data/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
